micronaut:
  application:
    name: mnQuickstart
  server:
    port: ${SERVER_PORT:8081}
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: changeThisSecretToALongSecureString
#              secret: ${JWT_SECRET:changeThisSecretToALongSecureString}
    # With that the static routes are available without auth
    reject-not-found: false

hello:
  world:
    message: "Hello from application.yml"
    translation:
      de: "Hallo Welt"
      en: "Hello World"
# JSON Settings
jackson:
  # property-naming-strategy: SNAKE_CASE
   serialization:
      writeDatesAsTimestamps: false
      writeDatesWithZoneId: true
      writeDateTimestampsAsNanoseconds: false
   deserialization:
      failOnUnknownProperties: false
   generator:
     writeNumbersAsStrings: false
     writeBigDecimalAsPlain: false